POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "type": "HealthCheck",
  "description": "a description",
  "date": "2022-07-12",
  "specialist": "a specialist",
  "diagnosisCodes": ["M51.2","J10.1"],
  "healthCheckRating": 2
}